FROM yongjhih/ubuntu-android-22

RUN echo "y" | android update sdk -u -a --filter android-23 && \
    echo "y" | android update sdk -u -a --filter build-tools-23.0.2 && \
    echo "y" | android update sdk -u -a --filter build-tools-23.0.1 && \
    echo "y" | android update sdk -u -a --filter build-tools-23.0.0
