FROM yongjhih/ubuntu-android

RUN echo "y" | android update sdk -u -a --filter platform-tools,extra-android-support,extra-android-m2repository,extra-google-google_play_services,extra-google-m2repository,extra-google-analytics_sdk_v2
